apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-avtaler-api
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 9090
  liveness:
    path: /sosialhjelp/avtaler-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/avtaler-api/internal/isReady
    initialDelay: 45
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/avtaler-api/internal/prometheus
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        groups:
          - id: "ec26a5a7-0909-40e4-b68f-8eb9c755aa77"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: sosialhjelp-avtaler-api-db
        tier: db-custom-1-3840
        diskSize: 10
        databases:
          - name: avtalerapidb
            envVarPrefix: POSTGRES
        cascadingDelete: false
    buckets:
      - name: digisos-nks-avtaler
        cascadingDelete: true
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-avtaler
        - application: sosialhjelp-avtaler-admin
    outbound:
      external:
        - host: data.brreg.no
        - host: api.signering.posten.no
        - host: pdl-api.prod-fss-pub.nais.io
        - host: secretmanager.googleapis.com
        - host: hooks.slack.com
        - host: ereg-services.dev-fss-pub.nais.io
        - host: konvertering-til-pdf.prod-fss-pub.nais.io
        - host: data.ssb.no
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  secureLogs:
    enabled: true
  envFrom:
    - secret: digisos-slack-hook
