apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 9090
  liveness:
    path: /sosialhjelp/avtaler-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/avtaler-api/internal/isReady
    initialDelay: 45
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/avtaler-api/internal/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  envFrom:
    - secret: redis-password-avtaler-api
    - secret: sosialhjelp-xsrf-secret
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        name: {{postgresUserName}}
        tier: db-f1-micro
        diskSize: 10
        databases:
          - name: {{postgresDatabaseName}}
            envVarPrefix: POSTGRES
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-avtaler-dev
    outbound:
      rules:
        - application: sosialhjelp-avtaler-dev
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
