apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamdigisos
  name: sosialhjelp-avtaler-api-redis
  namespace: teamdigisos
  annotations:
    "nais.io/run-as-group": "0"
    "nais.io/read-only-file-system": "false"
spec:
  image: bitnami/redis:6.0.16
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 2m
      memory: 32Mi
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-avtaler-api-dev
        - application: sosialhjelp-avtaler-api-mock
        - application: sosialhjelp-avtaler-api-redisexporter
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: redis-password-avtaler-api
