apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamdigisos
  name: sosialhjelp-avtaler-api-redisexporter
  namespace: teamdigisos
spec:
  image: oliver006/redis_exporter:v1.27.1
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 2m
      memory: 32Mi
  accessPolicy:
    outbound:
      rules:
        - application: sosialhjelp-avtaler-api-redis
  liveness:
    path: /health
  env:
    - name: REDIS_ADDR
      value: sosialhjelp-avtaler-api-redis:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
  envFrom:
    - secret: redis-password-avtaler-api
