apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-avtaler-api-dev
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 9090
  liveness:
    path: /sosialhjelp/avtaler-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/avtaler-api/internal/isReady
    initialDelay: 45
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/avtaler-api/internal/prometheus
  replicas:
    min: 1
    max: 2
  leaderElection: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        groups:
          - id: "9137b6c8-2023-4de9-87e0-0105f01c1e5d"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: sosialhjelp-avtaler-api-db-dev
        tier: db-f1-micro
        diskSize: 10
        databases:
          - name: avtalerapidb-dev
            envVarPrefix: POSTGRES
        cascadingDelete: false
    buckets:
      - name: digisos-nks-avtaler-dev
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-avtaler-dev
        - application: sosialhjelp-avtaler-admin
    outbound:
      external:
        - host: data.brreg.no
        - host: api.difitest.signering.posten.no
        - host: pdl-api.dev-fss-pub.nais.io
        - host: secretmanager.googleapis.com
        - host: hooks.slack.com
        - host: digisos.intern.dev.nav.no
        - host: ereg-services.dev-fss-pub.nais.io
        - host: data.ssb.no
      rules:
        - application: arbeidsgiver-altinn-tilganger
          namespace: arbeidsgiver
        - application: sosialhjelp-konvertering-til-pdf
  resources:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 15m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  envFrom:
    - secret: digisos-slack-hook
