name: Auto-deploy redis dev
on:
  push:
    paths:
      - "nais/redis-config.yml"
      - "nais/redisexporter.yml"
      - ".github/workflows/autodeploy_redis_dev.yml"
    branches-ignore:
      - 'main'
    tags-ignore:
      - "**"

jobs:
  deploy-dev-gcp:
    name: Auto-deploy redis to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
      - name: Deploye redis til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: dev-gcp
          TEAM: teamdigisos
          RESOURCE: "nais/redis-config.yml,nais/redisexporter.yml"
