name: Build image
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build kotlin, and run tests/lint
        uses: navikt/sosialhjelp-ci/actions/build-kotlin@master

      - name: Show git log
        run: echo "Git Log $(git log)"

      - name: Create and release tag
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master

      - name: Build and push Docker Image
        uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
        with:
          image-name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-version: ${{ steps.artifact-version.outputs.artifact-version }}
