name: Dependency Submission

on:
  push:
    branches:
      - main
  schedule: ## Kjører kl. 05:00 mandag -> fredag (schedule kjører bare for Default branch)
    - cron: '0 5 * * 1-5'

jobs:
  dependency_submission:
    name: Dependency Submission Gradle
    permissions:
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/dependency_submission_gradle.yml@master
