name: 'Dependency Submission Gradle'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'build.gradle.kts'

jobs:
  dependency_submission:
    name: Dependency Submission Gradle
    permissions:
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/dependency_submission_gradle.yml@v2