name: 'Deploy to Production'
on:
  workflow_run:
    workflows: [ 'Build Kotlin, Run Lint and Test' ]    # Venter på at bygg på master har kjørt uten feil
    branches: [ main ]
    types:
      - completed

jobs:
  deploy-to-prod:
    name: 'Deploy to prod-gcp'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      id-token: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_app.yml@v7
    with:
      cluster-name: 'prod-gcp'
      resource-folder: 'prod'
      resource-name: 'prod'
    secrets: inherit
