name: job-sync-tss
on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
jobs:
  run-job-lagre-digipost-dokumenter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Sett env variabler
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      - uses: nais/deploy/actions/deploy@v1
        name: run job sync-tss on ${{ inputs.cluster }}-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/nais-job-lagre-digipost-dokumenter.yaml
          CLUSTER: ${{ inputs.cluster }}-gcp
          VARS: nais/${{ inputs.cluster }}/${{ inputs.cluster }}.json
          REF: ${{ github.sha }}
          IMAGE: ${{ env.DOCKER_TAG }}
